//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayInn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Reseve_ID { get; set; }
        public Nullable<System.DateTime> Reseve_Date { get; set; }
        public string ResevedBY { get; set; }
        public Nullable<System.DateTime> Check_IN { get; set; }
        public Nullable<System.DateTime> Check_OUT { get; set; }
        public int NoOF_Adult { get; set; }
        public Nullable<int> NoOF_Kids { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> Room_No { get; set; }
    }
}
